### ISSUE TITLE
Vercel无法正常部署该项目

### ISSUE THREAD

**Issue by pyrrole-ach** [rockbenben/img-prompt#2]
使用Vercel部署时出现如下错误
![](https://aliyun.pyrroleach.com/utools/uTools_1686215637920.png)

**Comment by rockbenben** [comment]
上面的截图不完整。刚测试了下，Vercel部署是正常的。

**Comment by pyrrole-ach** [comment]
> 

感谢回复，目前问题已经解决。我是在您的项目下点击deploy直接部署的，按照下列步骤部署
![](https://aliyun.pyrroleach.com/utools/uTools_1686296994426.png)
---
![](https://aliyun.pyrroleach.com/utools/uTools_1686297028911.png)
---
![](https://aliyun.pyrroleach.com/utools/uTools_1686297072214.png)
![](https://aliyun.pyrroleach.com/utools/uTools_1686215637920.png)
然后就出现报错了，返回我的仓库发现仓库是已经创建好了，但是仓库里没有文件

我就用了另一种方式，先fork了您的项目，进入vercel新建一个项目，然后再拉取fork后的仓库就可以部署成功了
